name: Modern Android Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # السطر القاتل لخطأ نود:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # نستخدم v4 بدلاً من v2/v3 لتجنب خطأ نود
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          # البحث عن ملف التشغيل أينما كان ونقله للرئيسي
          find . -name gradlew -exec cp {} . \;
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: "**/build/outputs/apk/debug/*.apk"
